config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Validations
  validates_presence_of :content

  # Relationships
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  # Validations
  validates_presence_of :content

  # Relationships
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pagy::Backend
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[edit update destroy]

  def new
    @comment = @post.comments.new
    render 'form'
  end

  def create
    @comment = Comment.create(comment_params.merge(user_id: current_user.id, post_id: @post.id))

    if @post.save
      flash[:notice] = 'Comment was successfully created.'
      render 'comments/save'
    else
      flash[:error] = 'Comment failed to create.'
      render 'comments/save'
    end
  end

  def edit
    render 'form'
  end

  def update
    @comment.update_attributes(comment_params)

    if @comment.save
      flash[:notice] = 'Comment was successfully updated.'
      render 'comments/save'
    else
      flash[:error] = 'Comment failed to update.'
      render 'comments/save'
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post), notice: 'Comment was successfully deleted'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find_by(id: params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find_by(id: params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :fetch_post, only: %w[show edit update destroy]

  def index
    @pagy, @posts = pagy(Post.all.order('created_at DESC'), items: 10)
  end

  def new
    @post = Post.new
    render 'form'
  end

  def create
    @post = Post.create(post_params.merge(user_id: current_user.id))

    if @post.save
      flash[:notice] = 'Post was successfully created.'
      render 'posts/save'
    else
      flash[:error] = 'Post failed to create.'
      render 'posts/save'
    end
  end

  def show
    @comments = @post.comments
  end

  def edit
    render 'form'
  end

  def update
    @post.update_attributes(post_params)

    if @post.save
      flash[:notice] = 'Post was successfully updated.'
      render 'posts/save'
    else
      flash[:error] = 'Post failed to update.'
      render 'posts/save'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted'
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def fetch_post
    @post = Post.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<table class="table mt-4">
  <thead>
  <tr>
    <th scope="col">Commented By</th>
    <th scope="col">Comment</th>
    <th scope="col">Commented At</th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.user.username.titleize %></td>
      <td><%= comment.content %></td>
      <td><%= time_ago_in_words(comment.created_at) %> ago</td>
      <% if current_user.id == comment.user_id %>
        <td><%= link_to "Edit", edit_post_comment_path(@post, comment), class: "btn btn-secondary", remote: true %> </td>
        <td><%= link_to "Delete", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %> </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/comments/_form.html.erb
<div class="modal fade" id="commentFormModal" tabindex="-1" role="dialog" aria-labelledby="commentFormModalLable" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="commentFormModalLable">Comment Details</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for [ @post, @comment ], remote: true, :html => { :multipart => true } do |f| %>
        <div class="modal-body">
          <div class="form-group row">
            <label for="content" class="col-sm-12 col-form-label">Comment</label>
            <div class="col-sm-12">
              <%= f.text_area :content, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/form.js.erb
$('#displayModals').html("<%= j render 'form' %>")
$('#commentFormModal').modal('show');

app/views/comments/save.js.erb
<% if @comment.errors.any? %>
$("#commentFormModal").modal('hide');
$('#displayModals').html("<%= j render 'form' %>")
$("#commentFormModal").modal('show');
$('#flash-message').html("<%= j render 'layouts/shared/alert' %>")
<% else %>
window.location.reload()
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>

  <body>
  <div id="container">
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand bg-dark">
        <%= link_to "Home", posts_path, class: "navbar-brand" %>
        <div class="nav-item nav-link  ml-auto">
          <div class="dropdown">
            <button class="btn btn-light btn-md dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <strong><%= current_user.email %></strong>
            </button>
            <div class="dropdown-menu dropdown-menu-right bg-light" aria-labelledby="dropdownMenuButton">
              <button class="dropdown-item" type="button">
                <div class="text-center"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></div>
              </button>
            </div>
          </div>
        </div>
      </nav>
      <% else %>
      <nav class="navbar navbar-expand bg-dark">
        <div class="nav-item nav-link  ml-auto">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>
  </div>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container">
    <%= yield %>
    <div id="displayModals"></div>
  </div>
  </body>
</html>

app/views/layouts/shared/_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/posts/_form.html.erb
<div class="modal fade" id="postFormModal" tabindex="-1" role="dialog" aria-labelledby="postFormModalLable" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="postFormModalLable">Post Details</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for @post, remote: true, :html => { :multipart => true } do |f| %>
        <div class="modal-body">
          <div class="form-group row">
            <label for="content" class="col-sm-12 col-form-label">Post Content</label>
            <div class="col-sm-12">
              <%= f.text_area :content, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<table class="table mt-4">
  <thead>
  <tr>
    <th scope="col">Content</th>
    <th scope="col">Posted At</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.content, post_path(post.id) %></td>
      <td><%= time_ago_in_words(post.created_at) %> ago</td>
      <td><%= link_to "Delete", post_path(post), method: :delete, class: "btn btn-danger" %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/form.js.erb
$('#displayModals').html("<%= j render 'form' %>")
$('#postFormModal').modal('show');

app/views/posts/index.html.erb
<div class="row mt-4">
  <div class="col-sm">
    <%= link_to 'New Post', new_post_path, class: "btn btn-primary", remote: true %>
  </div>
</div>
<div class="row">
  <div class="col-sm">
    <%= render partial: 'posts' %>
  </div>
</div>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/posts/save.js.erb
<% if @post.errors.any? %>
$("#postFormModal").modal('hide');
$('#displayModals').html("<%= j render 'form' %>")
$("#postFormModal").modal('show');
$('#flash-message').html("<%= j render 'layouts/shared/alert' %>")
<% else %>
window.location.reload()
<% end %>

app/views/posts/show.html.erb
<div class="card mt-4" style="width: 100%;">
  <div class="card-body">
    <h5 class="card-title"><%= @post.user.username.titleize%></h5>
    <p class="card-text"><%= @post.content %></p>
  </div>
</div>

<div class="card mt-4" style="width: 100%;">
  <div class="col-sm mt-4">
    <%= link_to 'New Comment', new_post_comment_path(@post), class: "btn btn-primary", remote: true %>
  </div>
  <div class="row">
    <div class="col-sm">
      <%= render partial: 'comments/comments' %>
    </div>
  </div>
</div>